[package]
name = "cipher_file"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
pem = "3.0.4"
rsa = "0.9.6"
rand_core = "0.6.4"
clap = { version = "4.5", features = ["derive"] }
sha2 = "0.10.8"
aes-gcm = "0.10.3"
